- name: Install Snoopy
  shell: 'wget -O snoopy-install.sh https://github.com/a2o/snoopy/raw/install/doc/install/bin/snoopy-install.sh && chmod 755 snoopy-install.sh && ./snoopy-install.sh stable'
  register: Instalando snoopy 

- name: Iniciando Snoopy
  command: /usr/local/sbin/snoopy-enable
  register: Serviço iniciado

  #- name: Incluido server Rsyslog
  #lineinfile:
  #  path: /etc/rsyslog.conf
  #  line: '#Send Logs GRAYLOG'
  #  line: '*.*                                                     @172.31.42.197:10514'    

  #- name: Restart service
  #service:
  #  name: rsyslog
  #  state: restarted
